image: archlinux
packages:
  - jre-openjdk-headless
  - hut
  - unzip
oauth: pages.sr.ht/PAGES:RW
tasks:
  - build: |
      cd pace-calculator
      curl -fsSL https://bun.com/install | bash
      source /home/build/.bashrc
      bun install
      bun run build
  - package: |
      cd pace-calculator
      tar -C public -cvz . > site.tar.gz
  - upload: |
      cd pace-calculator
      # Only upload on the main branch.
      if [ "$(git rev-parse origin/main)" != "$(git rev-parse HEAD)" ]
      then
        echo "Not on main branch, not publishing!"
        exit 0
      fi
      hut pages publish --domain pc.vanburen.xyz site.tar.gz
