image: archlinux
packages:
  - nodejs
  - npm
  - jre-openjdk-headless
  - hut
sources:
  - https://git.sr.ht/~svbn/pace-calculator
oauth: pages.sr.ht/PAGES:RW
tasks:
  - build: |
      cd pace-calculator
      npm install
      npm run build
  - package: |
      cd pace-calculator
      tar -C public -cvz . > site.tar.gz
  - upload: |
      # Only upload on the main branch.
      if [ "$(git rev-parse origin/main)" != "$(git rev-parse HEAD)" ]
      then
        echo "Not on main branch, not publishing!"
        exit 0
      fi
      cd pace-calculator
      hut pages publish -d pc.vanburen.xyz site.tar.gz

