image: archlinux
packages:
  - jre-openjdk-headless
  - hut
  - nodejs
oauth: pages.sr.ht/PAGES:RW
tasks:
  - build: |
      curl https://mise.run | sh
      export PATH="$HOME/.local/bin:$HOME/.local/share/mise/shims:$PATH"
      mise use -g aube
      cd pace-calculator
      aube ci
      aube run build
  - package: |
      cd pace-calculator
      tar -C public -cvz . > site.tar.gz
  - upload: |
      cd pace-calculator
      # Only upload on the main branch.
      if [ "$(git rev-parse origin/main)" != "$(git rev-parse HEAD)" ]
      then
        echo "Not on main branch, not publishing!"
        exit 0
      fi
      hut pages publish --domain pc.vanburen.xyz site.tar.gz
